---
title: "Trabajo Final"
format: html
lang: es
author:
  name: "Martín Ceriotti"
  affiliation: "Universidad Austral"
editor: visual
toc: true
toc-location: left
toc-title: "Tabla de contenidos"
html:
    embed-resources: true
---

```{r}
#| label: carga
#| message: false
#| warning: false
#| include: false
#| paged-print: false
library(tidyverse)
library(pastecs)
library(kableExtra)
library(plotly)

maiz_serie_1923_2023 <- read_csv("../data/maiz-serie-1923-2023.csv",
  col_types = cols(anio = col_integer()),
  locale = locale(encoding = "latin1")
)

soja_serie_1941_2023 <- read_csv("../data/soja-serie-1941-2023.csv",
  col_types = cols(anio = col_integer()),
  locale = locale(encoding = "UTF-8")
)

trigo_serie_1927_2024 <- read_csv("../data/trigo-serie-1927-2024.csv",
  col_types = cols(anio = col_integer()),
  locale = locale(encoding = "latin1")
)
# Filtramos 1947 / 2023 para tener todos los cultivos todos los años y poder hacer otros análisis.
datos <- bind_rows(maiz_serie_1923_2023, soja_serie_1941_2023, trigo_serie_1927_2024) |>
  filter(anio >= 1947 & anio <= 2023)

# Parámetros para todos los ggplots.

theme_set(theme_light())
options(repr.plot.width = 15, repr.plot.height = 8)

# Evolución de las hectareas sembradas de cada cultivo.
```

```{r}
#| label: mapas
#| message: false
#| warning: false
#| include: false
#| paged-print: false
argentina <- sf::read_sf(
  dsn = "../mapas",                             #carpeta
  layer = "departamento"                     #nombre archivo
  )

provincias <- argentina %>% 
  filter(fdc %in% c("Servicio de Catastro e Información Territorial")) %>% 
  mutate(Nombre = str_wrap(nam, 8)) #separamos nombres largos en 2 lineas

soja <- datos |> 
  filter(provincia_nombre %in% c('Santa Fe'),
         cultivo_nombre == "soja",
         campania == "2018/2019")
trigo <- datos |> 
  filter(provincia_nombre %in% c('Santa Fe'),
         cultivo_nombre == "trigo",
         campania == "2018/2019")
maiz <- datos |> 
  filter(provincia_nombre %in% c('Santa Fe'),
         cultivo_nombre == "maíz",
         campania == "2018/2019")

maiz_gp <- provincias |> 
            left_join(maiz, by = c("in1" = "departamento_id")) 
trigo_gp <- provincias |> 
            left_join(trigo, by = c("in1" = "departamento_id")) 
soja_gp <- provincias |> 
            left_join(soja, by = c("in1" = "departamento_id")) 
```

#### Soja

::::: {style="display: flex;align-items: flex-center;"}
::: {style="flex: 7;"}
```{r, fig.width=20, fig.height=16 }
#| label: mapa soja
#| echo: false
#| message: false
#| warning: false
 
  ggplot(data = soja_gp) +
  aes(fill = rendimiento_kgxha) + 
  geom_sf() +
  geom_sf_label(aes(label = nam)) + 
  theme_set(theme_light()) 
    

```
:::

::: {style="flex: 3;"}
```{r}
#| label: grilla soja
#| echo: false
#| message: false
#| warning: false

soja |> 
  select(departamento_nombre, rendimiento_kgxha) |> 
  arrange(desc(rendimiento_kgxha)) |> 
  slice_head(n = 5) |> 
  kable(row.names = NA, col.names = NA)


```

En la campaña 2018/2019 el departamento Iriondo se destaca con los mayores rindes de soja.
:::
:::

::: {style="display: flex;align-items: flex-center;"}
::: {style="flex: auto;"}
#### Maíz

```{r, fig.width=20, fig.height=16 }
#| label: mapa maiz
#| echo: false
#| message: false
#| warning: false
 
  ggplot(data = maiz_gp) +
  aes(fill = rendimiento_kgxha) + 
  geom_sf() +
  geom_sf_label(aes(label = nam)) + 
  theme_set(theme_light()) + 
  scale_fill_gradient(low = "lightblue", high = "orange", name = "Rendimiento (kg/ha)")
    

```
:::
::: {style="flex: auto;"}
```{r}
#| label: grilla maiz
#| echo: false
#| message: false
#| warning: false

maiz |> 
  select(departamento_nombre, rendimiento_kgxha) |> 
  arrange(desc(rendimiento_kgxha)) |> 
  slice_head(n = 5) |> 
  kable(row.names = NA, col.names = NA)


```

En el caso del maíz, el departamento General López tuvo los mejores rendimientos.
:::
:::

::::: {style="display: flex;align-items: flex-center;"}
::: {style="flex: auto;"}
#### Trigo

```{r, fig.width=20, fig.height=16 }
#| label: mapa trigo
#| echo: false
#| message: false
#| warning: false
 
  ggplot(data = trigo_gp) +
  aes(fill = rendimiento_kgxha) + 
  geom_sf() +
  geom_sf_label(aes(label = nam)) + 
  theme_set(theme_light()) + 
  scale_fill_gradient(low = "lightgreen", high = "darkorange",  name = "Rendimiento (kg/ha)")
    

```
:::

::: {style="flex: auto;"}
```{r}
#| label: grilla trigo
#| echo: false
#| message: false
#| warning: false

trigo |> 
  select(departamento_nombre, rendimiento_kgxha) |> 
  arrange(desc(rendimiento_kgxha)) |> 
  slice_head(n = 5) |> 
  kable(row.names = NA, col.names = NA)


```

En el caso del trigo, tenemos los mismos resultados que para el Maíz, con General López destacado.
:::
:::::
